### ISSUE TITLE
DC offset removal (bug?)

### ISSUE THREAD

**Issue by ediooo** [sudosilico/sample-diffusion#10]
When I include the flag --remove_dc_offset postprocessing of the generated file crashes:

Filtering DC offset...
Traceback (most recent call last):
  File "/Users/XX/sample-diffusion/generate.py", line 246, in <module>
    main()
  File "/Users/XX/sample-diffusion/generate.py", line 24, in main
    audio_out = post_process_audio(
  File "/Users/XX/sample-diffusion/sample_diffusion/post_process.py", line 7, in post_process_audio
    audio_out = remove_dc_offset(audio_out, sample_rate)
TypeError: 'bool' object is not callable

Is this a bug or am I doing something wrong here?

**Comment by sudosilico** [comment]
Should be fixed with the latest commit.
